### ISSUE TITLE
[Question, Documentation] Explain How/Where This Might Be Used

### ISSUE THREAD

**Issue by chaojian-zhang** [os-js/osjs-json-config-cli#2]
Hi, the idea of using JSON as a configuration file sounds interesting. It seems that it's used not for system settings but for application settings?

I am having some difficulty understanding how this might be used, can you please provide more instructions?

Thanks!

**Comment by andersevenrud** [comment]
All this does is basically provide you with CLI commands to manipulate a JSON file, which can be used in the client and/or server.

This can be useful to automate writing configuration files as by default these are in javascript, which is not a very easy format to manipulate.
